# https://docs.readthedocs.io/en/stable/config-file/v2.html

version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.9"
  apt_packages:
    - ffmpeg

sphinx:
  builder: html
  configuration: docs/conf.py
  fail_on_warning: true

formats:
  - pdf

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
