name: PyPI

on:
  push:
    tags:
      - "*.*.*"
jobs:
  pypi:
    name: Upload to PyPI
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - run: pip install --upgrade build
      - run: pip install .[tests]
      - run: python -m pytest -v
      - run: python -m build
      - uses: pypa/gh-action-pypi-publish@release/v1
